version: 0.2

phases:
  build:
    commands:
      - mvn clean compile test

  post_build:
    commands:
      - echo "Its coming in this section"
      - aws sns publish --topic-arn arn:aws:sns:us-east-1:444082408997:Selenium_BDD_Framework_Email_with_Status_Report --message "Create Test Report and send the Email"

artifacts:
  files:
    - 'cucumber.html'
  base-directory: 'target/'
  name: cucumber.html