version: 0.2

phases:
  install:
    commands:
      # Installing linux dependencies
      - dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib
      # Installing Java 21
      - yes | sudo yum install java-22-amazon-corretto-devel
      - which -a java | xargs -I{} echo "echo {};{} -version;echo" | sh
      - echo 5 | sudo alternatives --config java
      - export JAVA_HOME=/usr/lib/jvm/java-22-amazon-corretto.x86_64/bin/java
      #Installing Maven
      - sudo wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      - sudo tar xvf apache-maven-3.9.9-bin.tar.gz -C /opt
      - sudo ln -s /opt/apache-maven-3.9.9 /opt/maven
      - mvn -version
      # Installing chrome
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - yes | sudo yum install ./google-chrome-stable_current_x86_64.rpm
      - sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chromium
      - curl https://intoli.com/install-google-chrome.sh | bash

  build:
    commands:
      mvn clean compile test